# Generated by Django 6.0.2 on 2026-02-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="menu_images/"),
        ),
    ]
