# Generated by Django 6.0.2 on 2026-02-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="friday",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="menu",
            name="monday",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="menu",
            name="saturday",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="menu",
            name="sunday",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="menu",
            name="thursday",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="menu",
            name="tuesday",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="menu",
            name="wednesday",
            field=models.TextField(blank=True),
        ),
    ]
