# Generated by Django 6.0.2 on 2026-02-11 14:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_customersubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customersubscription",
            name="end_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="customersubscription",
            name="payment_status",
            field=models.CharField(default="Paid", max_length=20),
        ),
        migrations.AlterField(
            model_name="customersubscription",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
