# Generated by Django 5.2.7 on 2026-02-13 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_customersubscription_end_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMealTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("Taken", "Taken"), ("Skipped", "Skipped")],
                        default="Taken",
                        max_length=10,
                    ),
                ),
                ("taken", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.AlterModelOptions(
            name="customersubscription",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="dailymenu",
            options={"ordering": ["day"]},
        ),
        migrations.AlterModelOptions(
            name="menu",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={"ordering": ["price"]},
        ),
        migrations.AddField(
            model_name="customersubscription",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="customersubscription",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="menu",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="menu",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="customersubscription",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailymenu",
            unique_together={("menu", "day")},
        ),
        migrations.AddConstraint(
            model_name="customersubscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("customer", "menu"),
                name="unique_active_subscription_per_customer_menu",
            ),
        ),
        migrations.AddField(
            model_name="dailymealtracking",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_tracking",
                to="core.customersubscription",
            ),
        ),
        migrations.AddIndex(
            model_name="dailymealtracking",
            index=models.Index(
                fields=["subscription", "date"], name="core_dailym_subscri_beb974_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailymealtracking",
            unique_together={("subscription", "date")},
        ),
    ]
